version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - FIRESTORE_CREDENTIALS=/app/serviceAccountKey.json
    volumes:
      - ./server/serviceAccountKey.json:/app/serviceAccountKey.json

  client:
    build: ./client
    depends_on:
      - server
    environment:
      - BOT_TOKEN=YOUR_TELEGRAM_BOT_TOKEN