version: "3.8"
services:
  server:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - FIRESTORE_CREDENTIALS=/app/serviceAccountKey.json
    volumes:
      - ./backend/serviceAccountKey.json:/app/serviceAccountKey.json

  client:
    build: ./frontend
    depends_on:
      - server
    env_file:
      - ./frontend/.env
        